import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "tutorial" }],
  referenceSidebar: [{ type: "autogenerated", dirName: "reference" }],
};

export default sidebars;
