name: "build offline version"
on:
  workflow_dispatch:
    inputs:
      commitHash:
        type: string
        required: true
        description: "commit hash"

      artifactPath:
        type: string
        required: true
        description: "artifact path"

      engineFeatures:
        type: string
        required: false
        description: "engine features"

      webhookUrl:
        type: string
        required: false
        description: "webhook url"

      webhookToken:
        type: string
        required: false
        description: "webhook token"

jobs:
  build-offline-version:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    env:
      ARITHMICO_FEATURES: ${{ inputs.engineFeatures }}
      WEBHOOK_URL: ${{ inputs.webhookUrl }}
      WEBHOOK_TOKEN: ${{ inputs.webhookToken }}

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: create ubuntu platform build job
        if: matrix.platform == 'ubuntu-20.04'
        shell: bash
        run: |
          curl -X POST '$WEBHOOK_URL' \
          -H 'Content-Type: application/json' \
          -d '{"platform": "linux", "webhookToken": "$WEBHOOK_TOKEN"}'

      - name: create macos platform build job
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          curl -X POST '$WEBHOOK_URL' \
          -H 'Content-Type: application/json' \
          -d '{"platform": "macos", "webhookToken": "$WEBHOOK_TOKEN"}'

      - name: create windows platform build job
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          curl -X POST '$WEBHOOK_URL' \
          -H 'Content-Type: application/json' \
          -d '{"platform": "windows", "webhookToken": "$WEBHOOK_TOKEN"}'

      - name: install frontend dependencies
        run: |
          node --version
          npm --version
          npm ci
          npx --no nx run calculator:build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "packages/applications/calculator"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: upload debian artefact
        if: matrix.platform == 'ubuntu-20.04'
        shell: bash
        env:
          BUCKET_ID: ${{ secrets.CDN_BUCKET }}
          ARTIFACT_PATH: ${{ inputs.artifactPath }}
        run: |
          FROM_PATH="./packages/applications/calculator/src-tauri/target/release/bundle/deb/arithmico-calculator_0.1.0_amd64.deb"
          DEST_PATH="s3://"$BUCKET_ID/$ARTIFACT_PATH".deb"
          aws s3 cp $FROM_PATH $DEST_PATH

      - name: upload windows artefact
        if: matrix.platform == 'windows-latest'
        shell: bash
        env:
          BUCKET_ID: ${{ secrets.CDN_BUCKET }}
          ARTIFACT_PATH: ${{ inputs.artifactPath }}
        run: |
          FROM_PATH="./packages/applications/calculator/src-tauri/target/release/bundle/nsis/Arithmico Calculator_0.1.0_x64-setup.exe"
          DEST_PATH="s3://"$BUCKET_ID/$ARTIFACT_PATH".exe"
          aws s3 cp "$FROM_PATH" $DEST_PATH

      - name: upload macos artefact
        if: matrix.platform == 'macos-latest'
        shell: bash
        env:
          BUCKET_ID: ${{ secrets.CDN_BUCKET }}
          ARTIFACT_PATH: ${{ inputs.artifactPath }}
        run: |
          FROM_PATH="./packages/applications/calculator/src-tauri/target/release/bundle/dmg/Arithmico Calculator_0.1.0_x64.dmg"
          DEST_PATH="s3://"$BUCKET_ID/$ARTIFACT_PATH".dmg"
          aws s3 cp "$FROM_PATH" $DEST_PATH
