on:
  create:
    tags:
      - "*"
  workflow_dispatch: {}

name: Build and Upload

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and Upload"
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
    steps:
      - name: Parse Git ref to tag
        id: get-tag
        shell: bash
        run: |
          TAG="${GITHUB_REF/refs\/tags\//""}"
          TAG="${TAG/refs\/heads\//""}"
          export TAG="${TAG/\//_}"
          echo "Tag is $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        name: Checkout

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: arithmico-api
          IMAGE_TAG: ${{ steps.get-tag.tag }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
